### ISSUE TITLE
Decoder loops forever when constructed with a non-array value

### ISSUE THREAD

**Issue by broofa** [dmonad/lib0#42]
**Describe the bug**
The following code loops forever due to `r` being undefined inside `readVarUint()`.

```
import { createDecoder, readVarUint } from 'lib0/decoding';

// Create a Blob (not an actual Blob, since they aren't a thing in Node, but
// let's pretend we have one like you get in the Browser)
const blob = { size: 20, type: '' };

const decoder = createDecoder('blob');
readVarUint(decoder);
```

**Expected behavior**
createDecoder() should throw if passed an unexpected value (such as a Blob)

... or something, anything, other than locking up the CPU/browser/system for all eternity. :-)

**Screenshots**
![CleanShot 2022-08-19 at 15 02 14@2x](https://user-images.githubusercontent.com/164050/185712974-28361503-5d79-44f3-b0d5-63d4646c5e11.png)

**Comment by dmonad** [comment]
Hi @broofa,

I understand where you are coming from. Many JavaScript libraries use ducktyping to "verify" that the input is of a specific type. 

Note that normal users don't have to interact with this library. I see lib0 more as an expert library, and I expect users who consume this library directly to use typescript, which would easily catch an issue like this. 

Ducktyping complicates the codebase and, personally, I don't see it as a good practice in JavaScript libraries. However, I see that expectations differ as a majority of npm packages still use ducktyping instead of adding proper type information.

**Comment by jamesopti** [comment]
So we are able to reproduce this easily (see below), based on a unit test we have for invalid input to a Y.Doc:

```ts
const Y = require('yjs')
const tempYdoc = new Y.Doc();
const ydocBytes = Buffer.from("garbage", "base64");
Y.applyUpdate(tempYdoc, ydocBytes);
// Hangs forever
```

> Note that normal users don't have to interact with this library. I see lib0 more as an expert library, and I expect users who consume this library directly to use typescript, which would easily catch an issue like this.

@dmonad Do you have a recommendation for how to validate input to `applyUpdate` before passing it in?
